/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AppTripsRouteImport } from './routes/_app/trips'
import { Route as AppRestaurantsRouteImport } from './routes/_app/restaurants'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCardsRouteImport } from './routes/_app/cards'
import { Route as AppTripsNewRouteImport } from './routes/_app/trips.new'
import { Route as AppTripsIdRouteImport } from './routes/_app/trips.$id'
import { Route as AppRestaurantsSlugRouteImport } from './routes/_app/restaurants.$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CountriesRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantsRoute = AppRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsNewRoute = AppTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsIdRoute = AppTripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppRestaurantsSlugRoute = AppRestaurantsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppRestaurantsRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/emergency': typeof EmergencyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/restaurants': typeof AppRestaurantsRouteWithChildren
  '/trips': typeof AppTripsRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/restaurants/$slug': typeof AppRestaurantsSlugRoute
  '/trips/$id': typeof AppTripsIdRoute
  '/trips/new': typeof AppTripsNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/emergency': typeof EmergencyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/restaurants': typeof AppRestaurantsRouteWithChildren
  '/trips': typeof AppTripsRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/restaurants/$slug': typeof AppRestaurantsSlugRoute
  '/trips/$id': typeof AppTripsIdRoute
  '/trips/new': typeof AppTripsNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/emergency': typeof EmergencyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/cards': typeof AppCardsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/restaurants': typeof AppRestaurantsRouteWithChildren
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/_app/restaurants/$slug': typeof AppRestaurantsSlugRoute
  '/_app/trips/$id': typeof AppTripsIdRoute
  '/_app/trips/new': typeof AppTripsNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assistant'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/countries'
    | '/emergency'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/cards'
    | '/dashboard'
    | '/restaurants'
    | '/trips'
    | '/checkout/success'
    | '/countries/$slug'
    | '/restaurants/$slug'
    | '/trips/$id'
    | '/trips/new'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assistant'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/countries'
    | '/emergency'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/cards'
    | '/dashboard'
    | '/restaurants'
    | '/trips'
    | '/checkout/success'
    | '/countries/$slug'
    | '/restaurants/$slug'
    | '/trips/$id'
    | '/trips/new'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/assistant'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/countries'
    | '/emergency'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_app/cards'
    | '/_app/dashboard'
    | '/_app/restaurants'
    | '/_app/trips'
    | '/checkout/success'
    | '/countries/$slug'
    | '/_app/restaurants/$slug'
    | '/_app/trips/$id'
    | '/_app/trips/new'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRouteWithChildren
  EmergencyRoute: typeof EmergencyRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurants': {
      id: '/_app/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof AppRestaurantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips/new': {
      id: '/_app/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AppTripsNewRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$id': {
      id: '/_app/trips/$id'
      path: '/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof AppTripsIdRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/restaurants/$slug': {
      id: '/_app/restaurants/$slug'
      path: '/$slug'
      fullPath: '/restaurants/$slug'
      preLoaderRoute: typeof AppRestaurantsSlugRouteImport
      parentRoute: typeof AppRestaurantsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRestaurantsRouteChildren {
  AppRestaurantsSlugRoute: typeof AppRestaurantsSlugRoute
}

const AppRestaurantsRouteChildren: AppRestaurantsRouteChildren = {
  AppRestaurantsSlugRoute: AppRestaurantsSlugRoute,
}

const AppRestaurantsRouteWithChildren = AppRestaurantsRoute._addFileChildren(
  AppRestaurantsRouteChildren,
)

interface AppTripsRouteChildren {
  AppTripsIdRoute: typeof AppTripsIdRoute
  AppTripsNewRoute: typeof AppTripsNewRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsIdRoute: AppTripsIdRoute,
  AppTripsNewRoute: AppTripsNewRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppRouteChildren {
  AppCardsRoute: typeof AppCardsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppRestaurantsRoute: typeof AppRestaurantsRouteWithChildren
  AppTripsRoute: typeof AppTripsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCardsRoute: AppCardsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppRestaurantsRoute: AppRestaurantsRouteWithChildren,
  AppTripsRoute: AppTripsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CountriesRouteChildren {
  CountriesSlugRoute: typeof CountriesSlugRoute
}

const CountriesRouteChildren: CountriesRouteChildren = {
  CountriesSlugRoute: CountriesSlugRoute,
}

const CountriesRouteWithChildren = CountriesRoute._addFileChildren(
  CountriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRouteWithChildren,
  EmergencyRoute: EmergencyRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
